/*
 * IRunOptionUIControl.java
 *
 * Created on 27 June 2008, 11:21
 */

package com.daffodil.documentumie.iebusiness.pimport.view;

import javax.swing.JCheckBox;

import com.daffodil.documentumie.iebusiness.AbstractUIControl;
import com.daffodil.documentumie.iebusiness.pimport.bean.ImportUIInfoBean;

/**
 *
 * @author  Administrator
 */
public class IRunOptionUIControl extends AbstractUIControl {
    
	String imageLocation;
	String showMessage;
    /** Creates new form IRunOptionUIControl */
    public IRunOptionUIControl() {
    	initComponents();
        initlizeUI();
    }
  
    
    @Override
	public void postInilize() {
   	getImportUIInfoBean().setIsLive(liveRun_JCheckBox.isSelected());
   	}
    
    private ImportUIInfoBean getImportUIInfoBean(){
		return (ImportUIInfoBean)getUiInfoBean();
	}

	@Override
	protected void preInilize() {
		liveRun_JCheckBox.setSelected(getImportUIInfoBean().getIsLive());
		
	}

	@Override
	public StringBuffer validateUIInputs() {
		// TODO Auto-generated method stub
		
		return null;
	}

	@Override
	public String getImageLocation() {
		imageLocation = "/com/daffodil/documentumie/iebusiness/pimport/view/images/heading_i_run.jpg";
		return imageLocation;
	}

	@Override
	public String getShowMessage() {
   	showMessage = "Select how you want to import the content ";
		return showMessage;
	}
	
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        liveRun_JCheckBox = new javax.swing.JCheckBox();
        
        setPreferredSize(new java.awt.Dimension(370, 355));
        setLayout(new java.awt.GridBagLayout());

        liveRun_JCheckBox.setOpaque(false);
        liveRun_JCheckBox.setText("Live Run");
        liveRun_JCheckBox.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(liveRun_JCheckBox, gridBagConstraints);

        
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox liveRun_JCheckBox;
   
    // End of variables declaration//GEN-END:variables
	@Override
	protected StringBuffer errorMessage() {
		// TODO Auto-generated method stub
		return null;
	}
	
    
}
