/*
 * IVerifyUIControl.java
 *
 * Created on 27 June 2008, 08:54
 */

package com.daffodil.documentumie.iebusiness.pimport.view;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import javax.swing.JButton;

import com.daffodil.documentumie.dctm.exception.DDfException;
import com.daffodil.documentumie.fileutil.logger.IELogger;
import com.daffodil.documentumie.fileutil.metadata.exception.DMetadataReadException;
import com.daffodil.documentumie.iebusiness.AbstractUIControl;
import com.daffodil.documentumie.iebusiness.pimport.bean.ImportUIInfoBean;
import com.daffodil.documentumie.iebusiness.pimport.controller.ImportController;
import com.daffodil.documentumie.iebusiness.pimport.model.ImportProcessor;

/**
 *
 * @author  Administrator
 */
public class IVerifyUIControl extends AbstractUIControl {

	String showMessage;
	String imageLocation;
	/** Creates new form IVerifyUIControl */
	public IVerifyUIControl() {
		initComponents();
		initlizeUI();
		
	}
	private void showforVerify() {
    	String verify = null;
    	verify =  " User Name: " +getImportUIInfoBean().getUserName()+" "+"\n";
    	verify += " Repository: " +getImportUIInfoBean().getRepository()+" "+"\n";
    	verify += " Object Type: "+getImportUIInfoBean().getObjectType()+" "+"\n";
    	verify += " Input Type: "+getImportUIInfoBean().getExtension()+" "+"\n";
    	verify += " Metadat File Input: "+getImportUIInfoBean().getMetadataInputFile()+" "+"\n";
    	verify += " Update Existing: "+getImportUIInfoBean().isUpdateExisting()+" "+"\n";
    	if(getImportUIInfoBean().getExtension().equalsIgnoreCase("xls")){
    	verify += " Excel Sheet: "+getImportUIInfoBean().getWorksheet()+" "+"\n";
    	}
    	verify += " Filter SQL: "+getImportUIInfoBean().getSql()+" "+"\n";
    	verify += " Live Run: "+getImportUIInfoBean().getIsLive()+" "+"\n";
    	
		verifyImportInput.setText(verify);
		verifyImportInput.setEditable(false);
	}


	@Override
	protected void preInilize() {
		String errorMessage = null;
		boolean fileExistanceFlag = checkFileExistance(getImportUIInfoBean().getSourceFileLocation());
		if (!fileExistanceFlag) {
				getIEMessageUtility().showMessageDialog(errorMessage.toString(), null);
				errorMessage = "Source input File does not existed";
				errorMessage = null;
		}else{
		showforVerify();
		}
	}

	private boolean checkFileExistance(String file_path) {
		boolean exist_not;
		if (file_path == null || "".equals(file_path != null ? file_path.trim() : "")) {
			return true;
		}
		File contentfile = new File(file_path);
		exist_not = contentfile.exists();
		return exist_not;
	}

	@Override
	public String getImageLocation() {
		imageLocation = "/com/daffodil/documentumie/iebusiness/pimport/view/images/heading_performing.jpg";
		return imageLocation;
	}

	@Override
	public String getShowMessage() {
		showMessage = "Verify your choices made during import wizard.";
		return showMessage;
	}

	private ImportUIInfoBean getImportUIInfoBean(){
		return (ImportUIInfoBean)getUiInfoBean();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		verifyImportInput_JScrollPane = new javax.swing.JScrollPane();
		verifyImportInput = new javax.swing.JTextArea();
		
		setPreferredSize(new java.awt.Dimension(370, 355));
		setLayout(new java.awt.GridBagLayout());

		verifyImportInput_JScrollPane.setPreferredSize(new java.awt.Dimension(250, 250));

//		verifyImportInput.setPreferredSize(new java.awt.Dimension(250, 250));

		verifyImportInput_JScrollPane.setViewportView(verifyImportInput);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
		verifyImportInput_JScrollPane.setViewportView(verifyImportInput);

		add(verifyImportInput_JScrollPane, gridBagConstraints);

	}// </editor-fold>//GEN-END:initComponents


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextArea verifyImportInput;
	private javax.swing.JScrollPane verifyImportInput_JScrollPane;
	// End of variables declaration//GEN-END:variables
	@Override
	protected void postInilize() {

	}
	@Override
	protected StringBuffer validateUIInputs() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	protected StringBuffer errorMessage() {
		// TODO Auto-generated method stub
		return null;
	}


}
