package com.daffodil.documentumie.iebusiness;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JScrollPane;

import com.daffodil.documentumie.fileutil.logger.IELogger;


public class IEMessageDialog extends javax.swing.JPanel {
	private JDialog mainDialog; 
	/** Creates new form IEMessageUtil 
	 * @param mainDialog */
	public IEMessageDialog() {
		initComponents();
		installlistenr();
		initUI();
	}

	private void initUI() {
		detail_JButton.setVisible(false);
		OK_JButton.setVisible(true);
		yes_JButton.setVisible(false);
		NO_JButton.setVisible(false);
		detail_JTextArea.setVisible(true);
	}

	private void installlistenr(){
//		detail_JButton.addActionListener(new ActionListener() {

//		public void actionPerformed(ActionEvent arg0) {

//		}
//		});
	}

	public void doDetailWork(){
		if(detail_JButton.getText().equalsIgnoreCase(">>")){
			detail_JScrollPane.setVisible(true);
			detail_JButton.setText("<<");
			setPreferredSize(new java.awt.Dimension(getSize().width, getSize().height+400));
		}else{
			detail_JScrollPane.setVisible(false);
			detail_JButton.setText(">>");
			setPreferredSize(new java.awt.Dimension(getSize().width, 300));
		}
	}

	public void setMessage(String msg, Throwable th){
		detail_JButton.setText(">>");
		message_JTextArea.setBorder(null);
		message_JTextArea.setText(msg);

		if(th!=null){
			detail_JTextArea.setText(th.toString());
			detail_JTextArea.setEditable(false);
//			message_JTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray));
		}
	}

	public void setLevel(int lvl){
		if(lvl == 1){
			detail_JButton.setVisible(false);
			OK_JButton.setVisible(true);
			yes_JButton.setVisible(false);
			NO_JButton.setVisible(false);
			detail_JScrollPane.setVisible(false);	
		}else if(lvl == 2){
			detail_JButton.setVisible(true);
			OK_JButton.setVisible(true);
			yes_JButton.setVisible(false);
			NO_JButton.setVisible(false);
			detail_JScrollPane.setVisible(false);	
		}else{
			detail_JButton.setVisible(false);
			OK_JButton.setVisible(false);
			yes_JButton.setVisible(true);
			NO_JButton.setVisible(true);
			detail_JScrollPane.setVisible(false);	
		}
	}
	public void registerListener(ActionListener l){
		OK_JButton.addActionListener(l);
		yes_JButton.addActionListener(l);
		NO_JButton.addActionListener(l);
		detail_JButton.addActionListener(l);
	}

	public void setImage(String path){
		icon_JLabel.setIcon(new ImageIcon(this.getClass().getResource(path)));
	}
	
	public void paintComponent(Graphics g) {

		Dimension dim = getSize();
		Graphics2D g2 = (Graphics2D) g;
		Insets inset = getInsets();
		int vWidth = dim.width - (inset.left + inset.right);
		int vHeight = dim.height - (inset.top + inset.bottom);

		paintGradient(g2, inset.left,
				inset.top, dim.width, dim.height, dim.height);
	}

	private void paintGradient(Graphics2D g2d, int x, int y,
			int w, int h, int height) {
		g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
				RenderingHints.VALUE_ANTIALIAS_ON);

		GradientPaint GP = new GradientPaint(0, h * 3 / 2, new Color(182, 183, 125), 0, h*1/2, new Color(255, 255, 255), true);
		g2d.setPaint(GP);

		g2d.setPaint(GP);
		g2d.fillRect(1, 1, w, h);

	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		message_JPanel = new javax.swing.JPanel();
		detail_JButton = new DButton(){

			@Override
			protected int getButtonWidth() {
				return 50;
			}

		};
		icon_JLabel = new javax.swing.JLabel();
		message_JTextArea = new javax.swing.JTextArea();
		message_JTextArea.setOpaque(false);
		detail_JScrollPane = new javax.swing.JScrollPane();
		detail_JTextArea = new javax.swing.JTextArea();
		button_JPanel = new javax.swing.JPanel();
		// message_JScrollPane = new JScrollPane();
		yes_JButton = new DButton() {
			protected int getButtonWidth() {
				return 55;
			}
		};

		NO_JButton = new DButton() {
			protected int getButtonWidth() {
				return 50;
			}
		};

		OK_JButton = new DButton() {
			protected int getButtonWidth() {
				return 50;
			}
		};

		setBackground(new java.awt.Color(255, 255, 255));
		setMinimumSize(new java.awt.Dimension(240, 90));
		//  setMaximumSize(new java.awt.Dimension(800, 900));
		// setPreferredSize(new java.awt.Dimension(240, 90));
		setLayout(new java.awt.GridBagLayout());
		setOpaque(false);
		message_JPanel.setMinimumSize(new java.awt.Dimension(240, 21));
		message_JPanel.setLayout(new java.awt.GridBagLayout());
		message_JPanel.setOpaque(false);

		detail_JButton.setText(">>");
		detail_JButton.setPreferredSize(new java.awt.Dimension(50, 20));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = gridBagConstraints.NORTH; 
		gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
		message_JPanel.add(detail_JButton, gridBagConstraints);

		icon_JLabel.setMinimumSize(new java.awt.Dimension(20, 20));
		icon_JLabel.setPreferredSize(new java.awt.Dimension(20, 20));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = gridBagConstraints.NORTH;
		gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
		message_JPanel.add(icon_JLabel, gridBagConstraints);



		message_JTextArea.setLineWrap(true);
		message_JTextArea.setMinimumSize(new java.awt.Dimension(130, 20));
		message_JTextArea.setPreferredSize(new java.awt.Dimension(130, 50));
		message_JTextArea.setEditable(false);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		message_JPanel.add(message_JTextArea, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		// gridBagConstraints.weighty = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
		add(message_JPanel, gridBagConstraints);

		detail_JScrollPane.setViewportView(detail_JTextArea);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
		gridBagConstraints.weighty = 6.0;
		gridBagConstraints.insets = new java.awt.Insets(2, 40, 0, 70);
		add(detail_JScrollPane, gridBagConstraints);

		button_JPanel.setLayout(new java.awt.GridBagLayout());
		button_JPanel.setOpaque(false);

		NO_JButton.setText("No");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
		gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 0);
		button_JPanel.add(NO_JButton, gridBagConstraints);

		OK_JButton.setText("Ok");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
		button_JPanel.add(OK_JButton, gridBagConstraints);

		yes_JButton.setText("Yes");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
		button_JPanel.add(yes_JButton, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		add(button_JPanel, gridBagConstraints);
	}// </editor-fold>                        


	// Variables declaration - do not modify                     
	private DButton NO_JButton;
	private DButton OK_JButton;
	private DButton yes_JButton;
	private javax.swing.JPanel button_JPanel;
	private DButton detail_JButton;
	private javax.swing.JLabel icon_JLabel;
	private javax.swing.JScrollPane detail_JScrollPane;
	private javax.swing.JTextArea message_JTextArea;
	private javax.swing.JTextArea detail_JTextArea;
	private javax.swing.JPanel message_JPanel;
	//   private JScrollPane message_JScrollPane;
	// End of variables declaration                   
	public JDialog getMainDialog() {
	return mainDialog;
	}

	public void setMainDialog(JDialog mainDialog) {
	this.mainDialog = mainDialog;
	}

}
