package com.daffodil.documentumie.iebusiness;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JPanel;


public abstract class ShowLogInformation extends JPanel {
   
	private static final long serialVersionUID = 1L;
    public ShowLogInformation(){
        initComponents();
        installlistener();
    }    
    
    private void installlistener(){
    	ok_JButton.addActionListener(new ActionListener(){

			public void actionPerformed(ActionEvent arg0) {
				doOnOKPress();				
			}
    	});
    }
    
    public void setText(String text){
    	logInfo_JTextArea.setText(text);
    }
    
    protected abstract void doOnOKPress(); 

    public void paintComponent(Graphics g) {

		Dimension dim = getSize();
		Graphics2D g2 = (Graphics2D) g;
		Insets inset = getInsets();
		int vWidth = dim.width - (inset.left + inset.right);
		int vHeight = dim.height - (inset.top + inset.bottom);

		paintGradient(g2, inset.left,
				inset.top, dim.width, dim.height, dim.height);
	}

	private void paintGradient(Graphics2D g2d, int x, int y,
			int w, int h, int height) {
		g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
				RenderingHints.VALUE_ANTIALIAS_ON);

		GradientPaint GP = new GradientPaint(0, h * 1 / 4, new Color(182, 183, 125), 0, h*3/4, new Color(255, 255, 255), true);
		g2d.setPaint(GP);

		g2d.setPaint(GP);
		g2d.fillRect(1, 1, w, h);

	}
	
	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
    	java.awt.GridBagConstraints gridBagConstraints;
    	
        setPreferredSize(new Dimension(350,350));

        textArea_JSCrollPane = new javax.swing.JScrollPane();
        logInfo_JTextArea = new javax.swing.JTextArea();
        ok_JButton = new DButton() {

			@Override
			protected int getButtonWidth() {
				return 80;
			}

		};

        setLayout(new java.awt.GridBagLayout());
        setOpaque(false);
        logInfo_JTextArea.setEditable(false);
        textArea_JSCrollPane.setViewportView(logInfo_JTextArea);
//        logInfo_JTextArea.setBackground(new Color(182, 183, 125));
//        logInfo_JTextArea.setForeground(new Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(textArea_JSCrollPane, gridBagConstraints);

        ok_JButton.setText("OK");
//        ok_JButton.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(ok_JButton, gridBagConstraints);
        
    }    
    
    private javax.swing.JTextArea logInfo_JTextArea;
    private javax.swing.JButton ok_JButton;
    private javax.swing.JScrollPane textArea_JSCrollPane;    
}
